name: Flutter Web CI

on:

  workflow_dispatch:
    inputs:
      flutterVersion:
        description: 'Flutter SDK version'
        required: false
        default: '3.22.0'

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ github.event.inputs.flutterVersion || '3.22.0' }}

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-flutter-

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter doctor
        working-directory: simple_live_app

      - name: Build Web App
        run: flutter build web --release
        working-directory: simple_live_app

      - name: Upload Web Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Web Build
          path: simple_live_app/build/web/
          retention-days: 14
